### ISSUE TITLE
why I can't use identityInterface class?

### ISSUE THREAD

**Issue by zieglar** [rmrevin/yii2-rbac-command#1]
hi @rmrevin ,
 this is my User model
class User extends \yii\db\ActiveRecord implements IdentityInterface {}

when I use `php yii`,
console tell me 'Exception 'yii\base\InvalidConfigException' with message '"api\models\User" refers to a api\models\User component. yii\web\User is expected.'', hwo to fix it?

my compontent.user is
`        'user' => [
            'identityClass' => 'api\models\User',
            'enableAutoLogin' => false,
            'enableSession' => false,
            'loginUrl' => null,
            'identityCookie' => ['name' => '_identity-drncd', 'httpOnly' => true],
        ],`

**Comment by rmrevin** [comment]
Hi. Show your `user` component config.

**Comment by zieglar** [comment]
'user' => [
            'identityClass' => 'api\models\User',
            'enableAutoLogin' => false,
            'enableSession' => false,
            'loginUrl' => null,
            'identityCookie' => ['name' => '_identity-drncd', 'httpOnly' =>
true],
        ],

开 2017年02月26日 在 17:12:57, Roman Revin (notifications@github.com) 写到:

component

**Comment by rmrevin** [comment]
Hi. Updated: show your full config of `user` component. 
```
VarDumper::dump(\Yii::$app->user, 1);
```
Where an exception is thrown?

**Comment by zieglar** [comment]
yii\web\User#1
(
    [identityClass] => 'api\\models\\User'
    [enableAutoLogin] => false
    [enableSession] => false
    [loginUrl] => null
    [identityCookie] => [
        'name' => '_identity-drncd'
        'httpOnly' => true
    ]
    [authTimeout] => null
    [accessChecker] => null
    [absoluteAuthTimeout] => null
    [autoRenewCookie] => true
    [idParam] => '__id'
    [authTimeoutParam] => '__expire'
    [absoluteAuthTimeoutParam] => '__absoluteExpire'
    [returnUrlParam] => '__returnUrl'
    [acceptableRedirectTypes] => [
        0 => 'text/html'
        1 => 'application/xhtml+xml'
    ]
    [yii\web\User:_access] => []
    [yii\web\User:_identity] => api\models\User#2
    (
        [yii\db\BaseActiveRecord:_attributes] => [
            'userID' => 1455643909160961044
            'name' => 'admin3'
            'password' =>
'$2y$13$gXLDw8Q80Ho4GpG9RFf1AuhAgiImwV1M5rEqMK1PW01Gthv7ED.u6'
            'phone' => '12345678904'
            'enabled' => true
            'group' => 'admin'
            'remarks' => null
            'authKey' => 'MOdNrFK6owzdLeWK_1EzVEhKUjaBclfv'
            'passwordResetToken' => null
            'createdAt' => '2017-02-22 14:51:37.965358'
            'updatedAt' => '2017-02-23 17:45:03'
            'deletedAt' => null
            'lastLogin' => '2017-02-24 18:09:42'
        ]
        [yii\db\BaseActiveRecord:_oldAttributes] => [
            'userID' => 1455643909160961044
            'name' => 'admin3'
            'password' =>
'$2y$13$gXLDw8Q80Ho4GpG9RFf1AuhAgiImwV1M5rEqMK1PW01Gthv7ED.u6'
            'phone' => '12345678904'
            'enabled' => true
            'group' => 'admin'
            'remarks' => null
            'authKey' => 'MOdNrFK6owzdLeWK_1EzVEhKUjaBclfv'
            'passwordResetToken' => null
            'createdAt' => '2017-02-22 14:51:37.965358'
            'updatedAt' => '2017-02-23 17:45:03'
            'deletedAt' => null
            'lastLogin' => '2017-02-24 18:09:42'
        ]
        [yii\db\BaseActiveRecord:_related] => []
        [yii\base\Model:_errors] => null
        [yii\base\Model:_validators] => null
        [yii\base\Model:_scenario] => 'default'
        [yii\base\Component:_events] => [
            'beforeInsert' => [
                0 => [
                    0 => [
                        0 => yii\behaviors\TimestampBehavior#3
                        (
                            [createdAtAttribute] => 'createdAt'
                            [updatedAtAttribute] => 'updatedAt'
                            [value] => Closure#4
                            (
                                [0] => Closure#4(...)
                            )
                            [attributes] => [
                                'beforeInsert' => [
                                    0 => 'createdAt'
                                    1 => 'updatedAt'
                                ]
                                'beforeUpdate' => 'updatedAt'
                            ]
                            [skipUpdateOnClean] => true
                            [owner] => api\models\User#2(...)
                        )
                        1 => 'evaluateAttributes'
                    ]
                    1 => null
                ]
            ]
            'beforeUpdate' => [
                0 => [
                    0 => [
                        0 => yii\behaviors\TimestampBehavior#3(...)
                        1 => 'evaluateAttributes'
                    ]
                    1 => null
                ]
            ]
        ]
        [yii\base\Component:_behaviors] => [
            0 => yii\behaviors\TimestampBehavior#3(...)
        ]
    )
    [yii\base\Component:_events] => []
    [yii\base\Component:_behaviors] => []
)

exception thrown when I use `php yii`

php yii
Exception 'yii\base\InvalidConfigException' with message '"api\models\User"
refers to a api\models\User component. yii\web\User is expected.'

in /Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/di/Instance.php:139

Stack trace:
#0
/Users/zieglar/Code/DrNCD/vendor/rmrevin/yii2-rbac-command/Command.php(90):
yii\di\Instance::ensure(Object(yii\di\Instance), 'yii\\web\\User')
#1 /Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/base/Object.php(107):
rmrevin\yii\rbac\Command->init()
#2 /Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/base/Controller.php(86):
yii\base\Object->__construct(Array)
#3 [internal function]: yii\base\Controller->__construct('rbac',
Object(yii\console\Application), Array)
#4 /Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/di/Container.php(375):
ReflectionClass->newInstanceArgs(Array)
#5 /Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/di/Container.php(156):
yii\di\Container->build('app\\commands\\Pr...', Array, Array)
#6 /Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/BaseYii.php(340):
yii\di\Container->get('app\\commands\\Pr...', Array)
#7 /Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/base/Module.php(578):
yii\BaseYii::createObject('app\\commands\\Pr...', Array)
#8
/Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/console/controllers/HelpController.php(196):
yii\base\Module->createController('')
#9
/Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/console/controllers/HelpController.php(288):
yii\console\controllers\HelpController->getCommandDescriptions()
#10
/Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/console/controllers/HelpController.php(67):
yii\console\controllers\HelpController->getDefaultHelp()
#11 [internal function]:
yii\console\controllers\HelpController->actionIndex(NULL)
#12
/Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/base/InlineAction.php(57):
call_user_func_array(Array, Array)
#13 /Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/base/Controller.php(156):
yii\base\InlineAction->runWithParams(Array)
#14
/Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/console/Controller.php(128):
yii\base\Controller->runAction('', Array)
#15 /Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/base/Module.php(523):
yii\console\Controller->runAction('', Array)
#16
/Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/console/Application.php(180):
yii\base\Module->runAction('', Array)
#17
/Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/console/Application.php(147):
yii\console\Application->runAction('', Array)
#18
/Users/zieglar/Code/DrNCD/vendor/yiisoft/yii2/base/Application.php(380):
yii\console\Application->handleRequest(Object(yii\console\Request))
#19 /Users/zieglar/Code/DrNCD/yii(27): yii\base\Application->run()
#20 {main}



开 2017年02月26日 在 17:18:30, Roman Revin (notifications@github.com) 写到:

Hi. Updated: show your full config of user component.

VarDumper::dump(\Yii::$app->user);

Where an exception is thrown?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rmrevin/yii2-rbac-command/issues/1#issuecomment-282543291>,
or mute the thread

**Comment by rmrevin** [comment]
Okay. Show your config of `rbac` console command.

**Comment by zieglar** [comment]
console/config/main-local.php is

<?php
return [
    'controllerMap' => [
        'rbac' => [
            'class' => 'app\commands\ProjectRbacCommand',
            'batchSize' => 1000,
            // 'forceAssign' => ['user'], // force assign user role for all
users
            // 'assignmentsMap' => [],
            'useTransaction' => true,
            'useCache' => true,
            'user' => 'api\models\User',
        ],
    ],
];

ProjectRbacCommand.php is copy from you ProjectRbacCommand.php, I put it in
console/commands



开 2017年02月26日 在 17:28:57, Roman Revin (notifications@github.com) 写到:

Okay. Show your config of rbac console command.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rmrevin/yii2-rbac-command/issues/1#issuecomment-282543784>,
or mute the thread

**Comment by rmrevin** [comment]
Remove line `'user' => 'api\models\User',`

**Comment by rmrevin** [comment]
There should be a reference to `user` component, not model.

**Comment by zieglar** [comment]
Still show exception to me
Exception 'yii\base\InvalidConfigException' with message '"api\models\User"
refers to a api\models\User component. yii\web\User is expected.'



开 2017年02月26日 在 17:34:36, Roman Revin (notifications@github.com) 写到:

Remove line 'user' => 'api\models\User',

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rmrevin/yii2-rbac-command/issues/1#issuecomment-282544066>,
or mute the thread

**Comment by rmrevin** [comment]
You did not specify these properties within `app\commands\ProjectRbacCommand`?

**Comment by zieglar** [comment]
Oh yes, I found this, when I remove , tell me Exception
'yii\base\InvalidConfigException' with message 'Failed to instantiate
component or class "user".'



开 2017年02月26日 在 17:38:44, Roman Revin (notifications@github.com) 写到:

You did not specify these properties within app\commands\ProjectRbacCommand?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rmrevin/yii2-rbac-command/issues/1#issuecomment-282544250>,
or mute the thread

**Comment by rmrevin** [comment]
In `console` application configuration specified `user` component?

**Comment by zieglar** [comment]
No, no user define in other config.




开 2017年02月26日 在 17:41:47, Roman Revin (notifications@github.com) 写到:

In console application configuration specify user component?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rmrevin/yii2-rbac-command/issues/1#issuecomment-282544379>,
or mute the thread

**Comment by rmrevin** [comment]
You need to add `user` component in console app configuration.

**Comment by zieglar** [comment]
Ok, thank you very much, it running. :)



开 2017年02月26日 在 17:50:05, Roman Revin (notifications@github.com) 写到:

You need to add user component in console app configuration.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rmrevin/yii2-rbac-command/issues/1#issuecomment-282544755>,
or mute the thread

**Comment by rmrevin** [comment]
I'm glad I could help )
